[package]
name = "sn_msg_dev"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "=2.8.4"
piltover = { git = "https://github.com/cartridge-gg/piltover.git", rev = "c25af3d" }

[[target.starknet-contract]]
sierra = true

[lib]
